name: ziggurat_sounds
version: 0.28.0
description: Provide sound support for [Ziggurat](https://github.com/chrisnorman7/ziggurat).
repository: https://github.com/chrisnorman7/ziggurat_sounds

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_synthizer: ^0.10.0
  encrypt: ^5.0.1
  json_annotation: ^4.5.0
  path: ^1.8.1
  ziggurat: ^0.48.0

dev_dependencies:
  analyzer: ^4.1.0
  build_runner: ^2.1.11
  dart_sdl: ^0.10.0
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.21.1
