name: ziggurat_sounds
version: 0.21.0
description: Provide sound support for [Ziggurat](https://github.com/chrisnorman7/ziggurat).
repository: https://github.com/chrisnorman7/ziggurat_sounds

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dart_synthizer: ^0.7.0
  encrypt: ^5.0.1
  json_annotation: ^4.4.0
  path: ^1.8.0
  ziggurat: ^0.41.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^6.0.0
  lints: ^1.0.1
  test: ^1.20.1
