name: ziggurat_sounds
description: Provide sound support for [Ziggurat](https://github.com/chrisnorman7/ziggurat).
version: 0.0.0
publish_to: none
# homepage: https://github.com/chrisnorman7/ziggurat_sounds

environment:
  sdk: ">=2.14.0-377.7.beta <3.0.0"

dependencies:
  dart_synthizer:
    git: https://github.com/chrisnorman7/dart_synthizer
  ziggurat:
    git: https://github.com/chrisnorman7/ziggurat

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.16.0
